# Init
version: '2'

networks:
  webservice:
    driver: bridge

volumes:
  systemdb:
    driver: local

services:
  systemdb:
    build:
      context: ./Docker/database/
      dockerfile: Dockerfile
      args:
        # Hardly recommanded to overide these at runtime
        - MYSQL_DATABASE=system
        - MYSQL_USER=system
        - MYSQL_PASSWORD=Syst3mP4ssw0rd!
        - MYSQL_ROOT_PASSWORD=Ch4ngeM3Qu1ckly!
    image: secudatabase
    hostname: systemdb.webservice
    volumes:
      - systemdb:/var/lib/mysql
    networks:
      webservice:
        aliases:
          - systemdb
          - systemdb.webservice

  systemweb:
    build:
      context: ./web/
      dockerfile: Dockerfile
    # Here mounting docker socket of the host to communicate with docker's API
    # volumes:

    ports:
      - "56080:1337"
    depends_on:
      - "systemdb"
    image: systemweb
    hostname: systemweb.webservice
    networks:
      webservice:
        aliases:
          - systemweb
          - systemweb.webservice
